config/routes.rb
Rails.application.routes.draw do
  get 'relations/new'

   resources :profiles
 
 devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  get 'pages/index'

  get 'pages/top'

  get 'pages/show'
  
  root 'pages#top'


 post 'relations/create' => 'relations#create'
 post 'relations/destroy' => 'relations#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SocialMatch',root_path,:class=>'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         
          <li>
            <a href="#">
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
            </a>
            </li>
            <li>
            <a href="#">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            </a>
            </li>            
            
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
              <span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
              <% if get_user_profile_id != nil %>
              <li><%=  link_to "プロフィールを編集", edit_profile_path(get_user_profile_id) %></li>
              <% else %>
              <li><%=  link_to "プロフィールを作成", new_profile_path(get_user_profile_id) %></li>
              <% end %>
              <li><%= link_to "設定変更", edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>        
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse --> 
 
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>social_match</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">
      <% if notice.present? %>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= notice %></p>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= alert %></p>
        </div>
      <% end %>

    <%= yield %>      
    </div>
  </body>
</html>